version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - my-network

  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    ports:
      - "5552:5552"
      - "15672:15672"
    env_file:
      - .env
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      retries: 5
      timeout: 2s

networks:
  my-network:
    name: my-network